In [12]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [4]:
datairis="https://raw.githubusercontent.com/cindylmr19/dataset/main/iris.csv"
iris=pd.read_csv(datairis)

In [5]:
iris.sample(150)

     sepallength  sepalwidth  petallength  petalwidth            class
58           6.6         2.9          4.6         1.3  Iris-versicolor
20           5.4         3.4          1.7         0.2      Iris-setosa
61           5.9         3.0          4.2         1.5  Iris-versicolor
94           5.6         2.7          4.2         1.3  Iris-versicolor
35           5.0         3.2          1.2         0.2      Iris-setosa
..           ...         ...          ...         ...              ...
141          6.9         3.1          5.1         2.3   Iris-virginica
109          7.2         3.6          6.1         2.5   Iris-virginica
90           5.5         2.6          4.4         1.2  Iris-versicolor
104          6.5         3.0          5.8         2.2   Iris-virginica
71           6.1         2.8          4.0         1.3  Iris-versicolor

[150 rows x 5 columns]

In [7]:
data1 = iris.drop(columns=['class'])
data1.head(150)

     sepallength  sepalwidth  petallength  petalwidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [9]:
dataNormalisasi = ['sepallength',	'sepalwidth',	'petallength',	'petalwidth']
FrameNormalisasi = data1[dataNormalisasi]
FrameNormalisasi

     sepallength  sepalwidth  petallength  petalwidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [13]:
scaler = MinMaxScaler()